# -*- coding: utf-8 -*-
"""
augur.llm_client - Optional OpenAI/DeepSeek LLM backend for persona chat.

When OPENAI_API_KEY is set and the `openai` SDK is installed, persona
chat responses are generated by the LLM using each persona's system prompt.
Otherwise the caller falls back to the template engine in chat.py.

Design:
    - is_llm_available(): cheap check (env key + SDK importable)
    - llm_persona_reply(): one persona reply from system prompt + history
    - Model: AUGUR_CHAT_MODEL env var, default gpt-4o.
    - Base URL: OPENAI_BASE_URL (defaults to OpenAI API if not set).
    - Fails soft: any error returns None so the caller can fall back.

Environment:
    OPENAI_API_KEY      - required to enable the LLM backend
    OPENAI_BASE_URL     - optional custom endpoint (e.g. for DeepSeek or local models)
    AUGUR_CHAT_MODEL    - optional model override (default: gpt-4o)
    AUGUR_CHAT_MAXTOK   - optional max output tokens (default: 1024)
"""

import os
import logging
from typing import List, Dict, Optional, Any

logger = logging.getLogger(__name__)

_DEFAULT_MODEL = "gpt-4o"
_DEFAULT_MAX_TOKENS = 1024

# Module-level client singleton (created lazily on first use)
_client = None
_client_failed = False


def _get_model() -> str:
    return os.environ.get("AUGUR_CHAT_MODEL", "").strip() or _DEFAULT_MODEL


def _get_max_tokens() -> int:
    try:
        return int(os.environ.get("AUGUR_CHAT_MAXTOK", "").strip() or _DEFAULT_MAX_TOKENS)
    except ValueError:
        return _DEFAULT_MAX_TOKENS


def is_llm_available() -> bool:
    """True when an API key is set and the openai SDK is importable."""
    if not os.environ.get("OPENAI_API_KEY", "").strip():
        return False
    try:
        import openai  # noqa: F401
        return True
    except ImportError:
        return False


def _get_client():
    """Lazily construct the OpenAI client; cache failures to avoid retries."""
    global _client, _client_failed
    if _client is not None:
        return _client
    if _client_failed:
        return None
    try:
        import openai
        api_key = os.environ.get("OPENAI_API_KEY", "").strip()
        base_url = os.environ.get("OPENAI_BASE_URL", "").strip() or None
        _client = openai.OpenAI(api_key=api_key, base_url=base_url)
        return _client
    except Exception as e:
        logger.warning("LLM client init failed: %s", e)
        _client_failed = True
        return None


def llm_persona_reply(
    system_prompt: str,
    history: List[Dict[str, str]],
    user_message: str,
    persona_name: str = "",
) -> Optional[str]:
    """
    Generate one persona reply via OpenAI-compatible API.

    Args:
        system_prompt: The persona's system prompt.
        history: Prior turns as [{"role": "user"|"assistant", "content": str}, ...].
        user_message: The new user message.
        persona_name: Display name, woven into the framing instruction.

    Returns:
        The reply text, or None on any failure (caller should fall back).
    """
    client = _get_client()
    if client is None:
        return None

    framing = (
        f"\n\n---\n你正在以「{persona_name}」的身份，在一个投资分析对话中回答用户提问。"
        if persona_name else
        "\n\n---\n你正在一个投资分析对话中以该投资人的身份回答用户提问。"
    )
    framing += (
        "\n请直接以第一人称、用该投资人的语气和投资框架回答，"
        "简洁有观点（2-4 段以内），不要输出思考过程或元评论。"
        "\n\n⚠️ 仅供学习研究，不构成投资建议。"
    )

    # Build messages
    messages: List[Dict[str, Any]] = [
        {"role": "system", "content": system_prompt + framing}
    ]

    for turn in history:
        role = turn.get("role")
        content = (turn.get("content") or "").strip()
        if role in ("user", "assistant") and content:
            messages.append({"role": role, "content": content})
            
    messages.append({"role": "user", "content": user_message.strip()})

    try:
        resp = client.chat.completions.create(
            model=_get_model(),
            messages=messages,
            max_tokens=_get_max_tokens(),
            temperature=0.7,
        )
        text = resp.choices[0].message.content
        return (text or "").strip() or None
    except Exception as e:
        logger.warning("LLM persona reply failed: %s", e)
        return None
