# -*- coding: utf-8 -*-
"""
augur.llm_client - Optional Claude LLM backend for persona chat.

When ANTHROPIC_API_KEY is set and the `anthropic` SDK is installed, persona
chat responses are generated by Claude using each persona's system prompt.
Otherwise the caller falls back to the template engine in chat.py.

Design:
    - is_llm_available(): cheap check (env key + SDK importable)
    - llm_persona_reply(): one persona reply from system prompt + history
    - Prompt caching: the long, stable persona system prompt carries a
      cache_control breakpoint so repeated turns reuse it (~0.1x cost).
    - Model: AUGUR_CHAT_MODEL env var, default claude-opus-4-8.
    - Fails soft: any error returns None so the caller can fall back.

Environment:
    ANTHROPIC_API_KEY   - required to enable the LLM backend
    AUGUR_CHAT_MODEL    - optional model override (default: claude-opus-4-8)
    AUGUR_CHAT_MAXTOK   - optional max output tokens (default: 1024)
"""

import os
import logging
from typing import List, Dict, Optional, Any

logger = logging.getLogger(__name__)

_DEFAULT_MODEL = "claude-opus-4-8"
_DEFAULT_MAX_TOKENS = 1024

# Module-level client singleton (created lazily on first use)
_client = None
_client_failed = False


def _get_model() -> str:
    return os.environ.get("AUGUR_CHAT_MODEL", "").strip() or _DEFAULT_MODEL


def _get_max_tokens() -> int:
    try:
        return int(os.environ.get("AUGUR_CHAT_MAXTOK", "").strip() or _DEFAULT_MAX_TOKENS)
    except ValueError:
        return _DEFAULT_MAX_TOKENS


def is_llm_available() -> bool:
    """True when an API key is set and the anthropic SDK is importable."""
    if not os.environ.get("ANTHROPIC_API_KEY", "").strip():
        return False
    try:
        import anthropic  # noqa: F401
        return True
    except ImportError:
        return False


def _get_client():
    """Lazily construct the Anthropic client; cache failures to avoid retries."""
    global _client, _client_failed
    if _client is not None:
        return _client
    if _client_failed:
        return None
    try:
        import anthropic
        _client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from env
        return _client
    except Exception as e:
        logger.warning("LLM client init failed: %s", e)
        _client_failed = True
        return None


def llm_persona_reply(
    system_prompt: str,
    history: List[Dict[str, str]],
    user_message: str,
    persona_name: str = "",
) -> Optional[str]:
    """
    Generate one persona reply via Claude.

    Args:
        system_prompt: The persona's system prompt (long, stable — gets cached).
        history: Prior turns as [{"role": "user"|"assistant", "content": str}, ...].
                 Must already alternate and start with a user turn (or be empty).
        user_message: The new user message.
        persona_name: Display name, woven into the framing instruction.

    Returns:
        The reply text, or None on any failure (caller should fall back).
    """
    client = _get_client()
    if client is None:
        return None

    # Frame the system prompt: persona prompt (cached) + a short, stable
    # final-answer instruction. Keeping this suffix byte-identical preserves
    # the cache prefix across turns.
    framing = (
        f"\n\n---\n你正在以「{persona_name}」的身份，在一个投资分析对话中回答用户提问。"
        if persona_name else
        "\n\n---\n你正在一个投资分析对话中以该投资人的身份回答用户提问。"
    )
    framing += (
        "\n请直接以第一人称、用该投资人的语气和投资框架回答，"
        "简洁有观点（2-4 段以内），不要输出思考过程或元评论。"
        "\n\n⚠️ 仅供学习研究，不构成投资建议。"
    )

    system_blocks = [
        {
            "type": "text",
            "text": system_prompt + framing,
            "cache_control": {"type": "ephemeral"},
        }
    ]

    # Build messages: prior history + new user turn. Defensive: ensure roles
    # alternate and the list starts with a user message.
    messages: List[Dict[str, Any]] = []
    for turn in history:
        role = turn.get("role")
        content = (turn.get("content") or "").strip()
        if role in ("user", "assistant") and content:
            messages.append({"role": role, "content": content})
    messages.append({"role": "user", "content": user_message.strip()})

    # Drop any leading assistant turns (API requires first message = user)
    while messages and messages[0]["role"] != "user":
        messages.pop(0)

    try:
        resp = client.messages.create(
            model=_get_model(),
            max_tokens=_get_max_tokens(),
            system=system_blocks,
            messages=messages,
        )
        text = next((b.text for b in resp.content if b.type == "text"), "")
        text = (text or "").strip()
        return text or None
    except Exception as e:
        logger.warning("LLM persona reply failed: %s", e)
        return None
